language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "pypy"
before_install:
  - sudo apt-get update && sudo apt-get install liblzma-dev
install:
  - "pip install -r requirements.txt"
  - "python setup.py install"
before_script:
  - "cd test"
script:
  - "python test_lzma.py"
#os:
# - linux
# - osx
#before_install:
#  - if [ "$TRAVIS_OS_NAME" == "linux"]; then sudo apt-get update && sudo apt-get install liblzma-dev; fi
#  - if [ "$TRAVIS_OS_NAME" == "osx"]; then brew update && brew install xz; fi
